version: '3.3'

services:
  database:
    container_name: ltcrx_postgres_db
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ltcrx_db
    ports:
      - 5434:5432


# to run
#  sudo docker-compose up database